export const STARTER_PLANTS = [
  {
    commonName: 'Tala', scientificName: 'Celtis tala', plantType: 'Tree', layer: 'Canopy',
    photos: ['./assets/plants/tala-1.jpg', './assets/plants/tala-2.jpg', './assets/plants/tala-3.jpg'],
    description: 'The keystone tree of the Buenos Aires region. Before the city existed, tala and ceibo were the dominant trees alongside the grasses. Small to medium sized, with dense, often thorny branching and small sweet fruits.',
    nativeStatus: 'Native to the Río de la Plata and Pampas region', nativeRange: 'Argentina, Uruguay, southern Brazil and neighboring areas',
    ecology: 'The defining tree of the talares, the native woodland of the region. Dense branching gives the canopy layer its structure, shelter and fruit. Drought tolerant and well suited to Buenos Aires soils.',
    purposes: ['Bird food','Shelter','Nesting','Edible'],
    wildlifeNotes: 'Critical for birds. Zorzales, celestinos, calandrias and dozens of other species depend on the berries. The dense branching doubles as cover and nesting structure.',
    sun: 'Full sun', water: 'Low to medium once established', soil: 'Adaptable; tolerates local soils and drought', size: 'Small to medium tree', fruiting: 'Small berries in the warm season',
    edibleUses: 'The berries are small, sweet and edible, with a flavour close to dates. The Querandí and Guaraní ate them.',
    medicinalUses: '', otherUses: '', safety: '',
    sources: 'Sendero de flora nativa, Jardín Botánico de Buenos Aires: https://buenosaires.gob.ar/gcaba_historico/jardinbotanico/senderofloranativa',
    status: 'Want', priority: 'High'
  },
  {
    commonName: 'Ceibo', scientificName: 'Erythrina crista-galli', plantType: 'Tree', layer: 'Canopy',
    photos: ['./assets/plants/ceibo-1.jpg', './assets/plants/ceibo-2.jpg', './assets/plants/ceibo-3.jpg'],
    description: 'The national flower of both Argentina and Uruguay. A spreading tree whose brilliant red flowers carry the whole spring and summer.',
    nativeStatus: 'Native to the Río de la Plata region', nativeRange: 'Argentina, Uruguay, Paraguay, southern Brazil',
    ecology: 'Associated with wetlands, river margins and low ground. A nitrogen-fixing legume, so it improves the soil for everything planted around it.',
    purposes: ['Hummingbirds','Pollinators','Shelter','Medicinal tradition'],
    wildlifeNotes: 'A hummingbird magnet in spring and summer. The picaflor común (Chlorostilbon lucidus) depends heavily on it, and large native bees work the same flowers.',
    sun: 'Full sun', water: 'Medium to high', soil: 'Tolerates moist and seasonally wet soils', flowering: 'Spring through the warm season',
    medicinalUses: 'In rioplatense medicine the bark tea is an astringent, antiseptic and sedative. Indigenous peoples used the bark on wounds and for toothache. The alkaloids erythraline and erysodine carry the sedative and anxiolytic action.',
    sources: 'Sendero de flora nativa, Jardín Botánico de Buenos Aires: https://buenosaires.gob.ar/gcaba_historico/jardinbotanico/senderofloranativa',
    status: 'Want', priority: 'High'
  },
  {
    commonName: 'Coronillo', scientificName: 'Scutia buxifolia', plantType: 'Tree', layer: 'Canopy',
    photos: ['./assets/plants/coronillo-1.jpg', './assets/plants/coronillo-2.jpg', './assets/plants/coronillo-3.jpg'],
    description: 'Evergreen tree or large shrub with dense, spiny branches and dark purple berries. Its presence is treated as an indicator of ecosystem health.',
    nativeStatus: 'Native to the Río de la Plata region', nativeRange: 'Argentina, Uruguay, southern Brazil',
    ecology: 'A core component of native woodland. The mariposa bandera argentina needs dense stands of it as a larval host, so scattered single plants are worth less than a group.',
    hostPlant: 'Mariposa bandera argentina (Morpho epistrophus argentinus)',
    purposes: ['Bird food','Shelter','Nesting','Butterflies'],
    wildlifeNotes: 'Several bird species build nests in the spiny branches, where the thorns deter predators. The dark purple berries feed celestinos, zorzal chalchalero and frutero azul among others.',
    sun: 'Full sun', water: 'Low to medium', soil: 'Adaptable, well-drained', fruiting: 'Dark purple berries',
    otherUses: 'The berries yield a dark dye. The wood is extremely hard and was traditionally used for fence posts that last decades.',
    sources: 'La biodiversidad urbana, Gobierno de la Ciudad de Buenos Aires: https://buenosaires.gob.ar/gcaba_historico/noticias/la-biodiversidad-urbana-el-corazon-verde-de-la-ciudad',
    status: 'Want', priority: 'High'
  },
  {
    commonName: 'Molle', scientificName: 'Schinus longifolia', plantType: 'Tree', layer: 'Canopy',
    photos: ['./assets/plants/molle-1.jpg', './assets/plants/molle-2.jpg', './assets/plants/molle-3.jpg'],
    description: 'A relative of the pink peppercorn tree, but native to the rioplatense region specifically rather than the Andes. Evergreen, so it holds cover all year.',
    nativeStatus: 'Native to the Río de la Plata region', nativeRange: 'Argentina, Uruguay and nearby South America',
    ecology: 'Evergreen woody habitat that adds year-round shelter and a long fruiting season to a native planting.',
    purposes: ['Bird food','Shelter','Medicinal tradition'],
    wildlifeNotes: 'The berries are eaten by more than twenty bird species, and the evergreen canopy provides cover through winter.',
    sun: 'Full sun', water: 'Low to medium', soil: 'Adaptable', fruiting: 'Small berries',
    edibleUses: 'The berries can be used as a pepper substitute.',
    medicinalUses: 'Indigenous peoples used the resin as an antiseptic and for dental pain.',
    status: 'Want'
  },
  {
    commonName: 'Ñangapirí / Pitanga', scientificName: 'Eugenia uniflora', plantType: 'Tree', layer: 'Fruit tree',
    photos: ['./assets/plants/nangapiri-1.jpg', './assets/plants/nangapiri-2.jpg', './assets/plants/nangapiri-3.jpg'],
    description: 'Ornamental evergreen tree of 3 to 10 metres, with fragrant white flowers and ribbed red to orange berries. The fruit is sweet-tart and strongly aromatic.',
    nativeStatus: 'Native to northeastern Argentina and the broader subtropical Río de la Plata region', nativeRange: 'Argentina, Uruguay, Paraguay, Brazil',
    ecology: 'Wild birds disperse the seed by eating the fruit, which is how it spreads through subtropical woodland.',
    hostPlant: 'Skipper butterfly Phocides polybius',
    purposes: ['Bird food','Pollinators','Butterflies','Edible','Medicinal tradition'],
    wildlifeNotes: 'Birds eat and disperse the fruit. The fragrant white flowers draw pollinators.',
    sun: 'Sun / partial shade', water: 'Medium', soil: 'Best in rich, well-drained soil', size: 'Approx. 3–10 m depending on conditions',
    flowering: 'Fragrant white flowers in spring', fruiting: 'Red to orange ribbed berries',
    propagation: 'Prefers some shelter while establishing. Once established it handles Buenos Aires cold well.',
    edibleUses: 'Sweet-tart and aromatic, loaded with lycopene, anthocyanins and vitamin C. Eat fresh, or use for jam, liqueur or ice cream.',
    medicinalUses: 'In Brazilian folk medicine the leaf tea is taken for diarrhoea, fever and high blood pressure. It carries significant antioxidant and antimicrobial activity.',
    sources: 'Árboles nativos, Gobierno de la Ciudad de Buenos Aires: https://buenosaires.gob.ar/gcaba_historico/arboles-nativos/nangapiri | Árboles nativos de Argentina, Argentina Forestal: https://www.argentinaforestal.com/2026/04/29/arboles-nativos-de-argentina/',
    status: 'Want', priority: 'High'
  },
  {
    commonName: 'Falso guayabo / Feijoa', scientificName: 'Acca sellowiana', plantType: 'Tree', layer: 'Fruit tree',
    photos: ['./assets/plants/feijoa-1.jpg', './assets/plants/feijoa-2.jpg', './assets/plants/feijoa-3.jpg'],
    description: 'Often assumed to be exotic, but native to southern Brazil, Uruguay and northeastern Argentina. Evergreen shrub or small tree with edible petals and aromatic green fruit that smells of pineapple, guava and mint.',
    nativeStatus: 'Native to southern South America, though not a Pampas endemic', nativeRange: 'Southern Brazil, Uruguay, parts of northeastern Argentina and Paraguay',
    ecology: 'Performs excellently around Buenos Aires, fruiting well and standing up to the local climate. Handles clay soils, organic soils and ground near waterways.',
    purposes: ['Bird food','Pollinators','Edible'],
    wildlifeNotes: 'Birds and bees both work the flowers heavily, and the fruit feeds wildlife as well.',
    sun: 'Full sun', water: 'Medium', soil: 'Adaptable; good in clay, organic soils and near water', flowering: 'Showy flowers with fleshy petals', fruiting: 'Aromatic green fruit',
    edibleUses: 'The fruit is rich in vitamin C and unusually rich in iodine for a fruit. The petals are sweet and can be eaten straight off the tree.',
    sources: 'Árboles nativos de Argentina, Argentina Forestal: https://www.argentinaforestal.com/2026/04/29/arboles-nativos-de-argentina/',
    status: 'Want'
  },
  {
    commonName: 'Arazá', scientificName: 'Psidium cattleianum', plantType: 'Tree', layer: 'Fruit tree',
    photos: ['./assets/plants/araza-1.jpg', './assets/plants/araza-2.jpg', './assets/plants/araza-3.jpg'],
    description: 'A guava relative native to the region, with small, intensely aromatic fruit in red or yellow forms.',
    nativeStatus: 'Native to southeastern South America, outside the core Pampas', nativeRange: 'Brazil and neighboring subtropical South America',
    ecology: 'A fruiting understorey and edge tree of subtropical woodland, spread by fruit-eating birds.',
    purposes: ['Bird food','Pollinators','Edible'],
    wildlifeNotes: 'Fruit-eating birds take the berries readily. The flowers draw pollinators.',
    sun: 'Full sun', water: 'Medium', soil: 'Well-drained, fertile soil', fruiting: 'Small red or yellow fruit',
    edibleUses: 'Excellent fresh, and for juice and preserves. Native fruits like this one are being researched for nutraceutical value: they carry very high levels of antioxidant compounds linked to prevention of cardiovascular disease.',
    sources: 'Frutales originarios de Argentina y países limítrofes, Huertas Urbanas: https://www.huertasurbanas.com/2012/06/05/frutales-originarios-de-argentina-y-paises-limitrofes/',
    status: 'Want'
  },
  {
    commonName: 'Congorosa', scientificName: 'Monteverdia ilicifolia', plantType: 'Shrub', layer: 'Shrub',
    photos: ['./assets/plants/congorosa-1.jpg', './assets/plants/congorosa-2.jpg', './assets/plants/congorosa-3.jpg'],
    description: 'Arguably the most pharmacologically validated native medicinal plant of the Southern Cone. A holly-like evergreen shrub, very ornamental. Older references use the name Maytenus ilicifolia.',
    nativeStatus: 'Native to the Southern Cone', nativeRange: 'Argentina, Paraguay, Uruguay, Brazil',
    ecology: 'Evergreen shrub-layer structure with berries for birds and dense spiny foliage for cover.',
    purposes: ['Bird food','Shelter','Medicinal tradition'],
    wildlifeNotes: 'The berries feed birds and the evergreen, spiny structure gives them protected cover.',
    sun: 'Sun / partial shade', water: 'Medium', soil: 'Adaptable',
    propagation: 'Leaves can be harvested continuously for tea once the shrub is established.',
    medicinalUses: 'Known to the indigenous peoples of the region for hundreds of years. It is in the 4th edition of the Brazilian Pharmacopoeia and on Brazil simplified registration list for herbal medicines. A leaf and stem decoction, added to mate or drunk as tea, is used in Argentina for gastric ulcers, high blood pressure and joint pain. The active compounds maytenin, pristimerin and friedelanol show antiulcer activity comparable to ranitidine in clinical studies.',
    sources: 'Plantas medicinales autóctonas, Todo Uruguay: https://www.todouruguay.net/plantas-medicinales-autoctonas/',
    status: 'Want', priority: 'High'
  },
  {
    commonName: 'Carqueja', scientificName: 'Baccharis trimera / Baccharis articulata', plantType: 'Herb', layer: 'Herbaceous',
    photos: ['./assets/plants/carqueja-1.jpg', './assets/plants/carqueja-2.jpg', './assets/plants/carqueja-3.jpg'],
    description: 'A strange-looking plant with flat, winged green stems and no apparent leaves. One of the most important medicinal plants of the Río de la Plata.',
    nativeStatus: 'Native to southern South America', nativeRange: 'Argentina, Uruguay, Paraguay, Brazil',
    ecology: 'Grows in poor soils and tolerates drought, filling the herbaceous layer where little else establishes.',
    purposes: ['Pollinators','Medicinal tradition'],
    wildlifeNotes: 'Attracts native pollinators when flowering.',
    sun: 'Full sun', water: 'Low to medium', soil: 'Tolerates poor soils',
    medicinalUses: 'Taken as an infusion or decoction for digestive and liver-protective purposes, traditionally 2 to 3 cups daily before meals. It is also mixed straight into mate at roughly 1 part carqueja to 5 or 10 parts yerba, a common folk preparation in Argentina and Uruguay. It is hepatoprotective, anti-inflammatory, hypoglycemic and gastroprotective.',
    otherUses: 'Several Baccharis species share the name carqueja. B. trimera and B. articulata are both used.',
    sources: 'Carqueja, Liluama: https://liluama.pe/plantas/carqueja/',
    status: 'Want'
  },
  {
    commonName: 'Marcela', scientificName: 'Achyrocline satureioides', plantType: 'Herb', layer: 'Herbaceous',
    photos: ['./assets/plants/marcela-1.jpg', './assets/plants/marcela-2.jpg', './assets/plants/marcela-3.jpg'],
    description: 'One of the most widely used medicinal plants in South America, and especially in the Río de la Plata basin. Silver-grey foliage with clusters of small pale flowers.',
    nativeStatus: 'Native to southern South America', nativeRange: 'Argentina, Uruguay, Paraguay, Brazil',
    ecology: 'A grassland herb of lean, well-drained ground, flowering late in the warm season.',
    purposes: ['Pollinators','Medicinal tradition'],
    wildlifeNotes: 'The flower heads feed small pollinators.',
    sun: 'Full sun', water: 'Low to medium', soil: 'Well-drained; handles lean conditions',
    medicinalUses: 'Used for digestive complaints, and as an antiseptic, anti-inflammatory and antioxidant. Its digestive, antimicrobial and antiviral activity against several human pathogens comes from caffeoylquinic acids and flavonoids. It is hypoglycemic, and significantly reduces brain damage from cerebrovascular accidents. Indigenous peoples used it macerated to reduce body weight.',
    otherUses: 'The dried flowers keep their fragrance for years. Traditionally hung in closets and placed under pillows.',
    sources: 'Plantas medicinales autóctonas, Todo Uruguay: https://www.todouruguay.net/plantas-medicinales-autoctonas/ | Hierbas medicinales de Argentina, Enlace Crítico: https://www.enlacecritico.com/salud/hierbas-medicinales-de-argentina/',
    status: 'Want'
  },
  {
    commonName: 'Sen del campo', scientificName: 'Senna corymbosa', plantType: 'Shrub', layer: 'Shrub',
    photos: ['./assets/plants/sen-del-campo-1.jpg', './assets/plants/sen-del-campo-2.jpg', './assets/plants/sen-del-campo-3.jpg'],
    description: 'Native shrub carrying brilliant yellow flowers straight through summer and autumn.',
    nativeStatus: 'Native to southern South America', nativeRange: 'Argentina, Uruguay, southern Brazil and neighboring regions',
    ecology: 'A long-flowering shrub-layer legume that bridges the gap between the spring and late-season nectar plants.',
    purposes: ['Butterflies','Pollinators','Hummingbirds','Medicinal tradition'],
    wildlifeNotes: 'Attracts sulphur butterflies and bees through summer and autumn. Hummingbirds visit it too.',
    sun: 'Full sun', water: 'Low to medium', soil: 'Adaptable, well-drained', flowering: 'Summer into autumn', fruiting: 'Slender green seed pods',
    medicinalUses: 'The leaves are used as a gentle laxative, similar in effect to commercial senna.',
    status: 'Want'
  },
  {
    commonName: 'Lantana', scientificName: 'Lantana camara', plantType: 'Shrub', layer: 'Shrub',
    photos: ['./assets/plants/lantana-1.jpg', './assets/plants/lantana-2.jpg', './assets/plants/lantana-3.jpg'],
    description: 'Native to this region, despite being widely assumed exotic. The multi-coloured flower clusters are absolute butterfly and hummingbird magnets.',
    nativeStatus: 'Regionally native, though the species is spread across the tropical and subtropical Americas. Nursery stock is often garden hybrid, so ask about provenance.',
    nativeRange: 'Tropical and subtropical Americas, including this region',
    ecology: 'A shrub-layer nectar source that flowers for months, followed by berries for birds.',
    purposes: ['Bird food','Butterflies','Pollinators','Hummingbirds','Medicinal tradition'],
    wildlifeNotes: 'One of the strongest butterfly plants available, and a reliable hummingbird draw. The berries feed birds.',
    sun: 'Full sun', water: 'Low to medium', soil: 'Adaptable', flowering: 'Long warm-season display',
    medicinalUses: 'A leaf infusion is used for respiratory complaints and fever.',
    safety: 'Leaves and unripe berries are toxic if eaten. Worth knowing where children or pets browse.',
    status: 'Want'
  },
  {
    commonName: 'Salvia guaranítica', scientificName: 'Salvia guaranitica', plantType: 'Herb', layer: 'Herbaceous',
    photos: ['./assets/plants/salvia-guaranitica-1.jpg', './assets/plants/salvia-guaranitica-2.jpg', './assets/plants/salvia-guaranitica-3.jpg'],
    description: 'Deep blue tubular flowers on a vigorous perennial. The single best hummingbird plant you can grow in Buenos Aires.',
    nativeStatus: 'Native to southern South America', nativeRange: 'Argentina, Uruguay, Paraguay, Brazil',
    ecology: 'Spreads into dense clumps and blooms for months, giving the herbaceous layer a long nectar season.',
    purposes: ['Hummingbirds','Pollinators','Medicinal tradition'],
    wildlifeNotes: 'Multiple observers confirm that salvia guaranítica planted in quantity produces abundant hummingbird visits right through the warm season. Plant it in a block rather than as single plants.',
    sun: 'Sun / partial shade', water: 'Medium', soil: 'Adaptable, prefers reasonably drained soil', flowering: 'Warm season, often for many months',
    propagation: 'Easy from cuttings, and spreads on its own into dense clumps.',
    medicinalUses: 'The Guaraní used it as an anti-inflammatory and for skin conditions.',
    sources: 'Picaflores de la plaza, Aves Bonaerenses: http://avesbonaerenses.blogspot.com/2014/03/picaflores-de-la-plaza.html',
    status: 'Want', priority: 'High'
  },
  {
    commonName: 'Pasionaria / Mburucuyá', scientificName: 'Passiflora caerulea', plantType: 'Climber', layer: 'Climber',
    photos: ['./assets/plants/pasionaria-1.jpg', './assets/plants/pasionaria-2.jpg', './assets/plants/pasionaria-3.jpg'],
    description: 'The native passion flower. A vigorous climber with spectacular flowers and edible orange fruit.',
    nativeStatus: 'Native to the Río de la Plata and surrounding South American region', nativeRange: 'Argentina, Uruguay, Paraguay, Brazil and nearby regions',
    ecology: 'Climbs through the shrub and canopy layers, and is the exclusive larval host for several Heliconius butterflies.',
    hostPlant: 'Exclusive host plant for several Heliconius butterfly species',
    purposes: ['Butterflies','Pollinators','Edible','Medicinal tradition'],
    wildlifeNotes: 'Host vine for native passion-vine butterflies, and the flowers are worked heavily by pollinators.',
    sun: 'Sun / partial shade', water: 'Medium', soil: 'Adaptable with good drainage', flowering: 'Warm season', fruiting: 'Small orange fruit',
    propagation: 'Seed, cuttings and suckers.',
    edibleUses: 'The fruit is small but edible and aromatic, less fleshy than cultivated passionfruit.',
    medicinalUses: 'The anxiolytic effect comes from chrysin. This is one of the best-documented natural anxiolytics in the world, used in herbal medicine across South America and now in European phytotherapy.',
    sources: 'Plantas medicinales autóctonas de la Argentina, Talapampa: http://www.talapampa.com/plantas_medicinales_autoctonas_de_la_argentina.pdf',
    status: 'Want', priority: 'High'
  },
  {
    commonName: 'Fosforito / Bandera española', scientificName: 'Dicliptera tweediana', plantType: 'Herb', layer: 'Herbaceous',
    photos: ['./assets/plants/dicliptera-1.jpg', './assets/plants/dicliptera-2.jpg'],
    description: 'A low herbaceous plant with bright tubular red-orange flowers that hummingbirds adore. Very easy to grow.',
    nativeStatus: 'Native to the Río de la Plata region', nativeRange: 'Argentina, Uruguay and nearby areas',
    ecology: 'Fills the shaded herbaceous layer, where most hummingbird plants will not flower.',
    purposes: ['Hummingbirds','Pollinators'],
    wildlifeNotes: 'The tubular flowers are shaped for hummingbirds and they use them heavily.',
    sun: 'Partial shade', water: 'Medium', soil: 'Adaptable', flowering: 'Warm season',
    propagation: 'Easy in shade or partial shade; one of the simplest natives to establish.',
    status: 'Want', priority: 'High'
  },
  {
    commonName: 'Cortadera / Pampas grass', scientificName: 'Cortaderia selloana', plantType: 'Grass', layer: 'Grass',
    photos: ['./assets/plants/cortadera-1.jpg', './assets/plants/cortadera-2.jpg', './assets/plants/cortadera-3.jpg'],
    description: 'The large native tussock grass of the Pampas, with tall silver flowering plumes.',
    nativeStatus: 'Native to southern South America', nativeRange: 'Argentina, Uruguay, southern Brazil and nearby regions',
    ecology: 'Native grasses are the backbone of this landscape. They feed seed-eating birds, supply nesting material and shelter ground-dwelling insects.',
    purposes: ['Bird food','Shelter','Nesting'],
    wildlifeNotes: 'Seed for finches, sparrows and other seed-eaters. The dense tussock provides nesting material and habitat for ground-dwelling insects.',
    sun: 'Full sun', water: 'Low to medium', soil: 'Very adaptable', size: 'Large clump; allow substantial space', flowering: 'Tall plumes in late summer and autumn',
    safety: 'The leaf edges cut. Site it away from paths and places where people brush past.',
    status: 'Want'
  },
  {
    commonName: 'Flechilla', scientificName: 'Nassella spp. (formerly many Stipa spp.)', plantType: 'Grass', layer: 'Grass',
    photos: ['./assets/plants/flechilla-1.jpg', './assets/plants/flechilla-2.jpg', './assets/plants/flechilla-3.jpg'],
    description: 'The fine-leaved bunchgrasses that characterise Pampas grassland, named for the arrow-like seeds.',
    nativeStatus: 'Many species are native to the Pampas; identify the exact species before planting', nativeRange: 'Pampas and other South American grasslands, depending on species',
    ecology: 'Native grasses are the backbone of this landscape. They feed seed-eating birds, supply nesting material and shelter ground-dwelling insects.',
    purposes: ['Bird food','Shelter','Nesting'],
    wildlifeNotes: 'Seed for finches, sparrows and other seed-eaters, plus nesting material and habitat for ground-dwelling insects.',
    sun: 'Full sun', water: 'Low', soil: 'Well suited to open, often lean grassland soils', flowering: 'Seedheads through the warm season',
    status: 'Want'
  },
  {
    commonName: 'Cola de zorro', scientificName: 'Setaria spp.', plantType: 'Grass', layer: 'Grass',
    photos: ['./assets/plants/cola-de-zorro-1.jpg', './assets/plants/cola-de-zorro-2.jpg', './assets/plants/cola-de-zorro-3.jpg'],
    description: 'Foxtail grasses, named for the dense cylindrical seedheads. The common name covers several species.',
    nativeStatus: 'Some Setaria are native and others introduced; verify the exact species', nativeRange: 'Depends on species',
    ecology: 'Native grasses are the backbone of this landscape. They feed seed-eating birds, supply nesting material and shelter ground-dwelling insects.',
    purposes: ['Bird food','Shelter','Nesting'],
    wildlifeNotes: 'The seedheads feed finches, sparrows and other granivorous birds, and the clumps shelter ground-dwelling insects.',
    sun: 'Full sun', water: 'Low to medium', soil: 'Adaptable', flowering: 'Spike-like seedheads in the warm season',
    status: 'Want'
  }
];
