// Regenerates the app's generated files from content/.
// Run with: npm run build
import {readFile, readdir, writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT = path.join(ROOT, 'content', 'plants');
const PHOTO_DIR = path.join(ROOT, 'assets', 'plants');

const PLANT_FIELDS = ['commonName','scientificName','plantType','layer','description','nativeStatus','nativeRange',
  'ecology','hostPlant','purposes','wildlifeNotes','sun','water','soil','size','flowering','fruiting','propagation',
  'edibleUses','medicinalUses','otherUses','safety','sources','status','priority'];

export async function loadPlants() {
  const order = JSON.parse(await readFile(path.join(ROOT, 'content', 'order.json'), 'utf8')).order;
  const files = (await readdir(CONTENT)).filter(name => name.endsWith('.json')).map(name => name.slice(0, -5));
  const slugs = [...order.filter(slug => files.includes(slug)), ...files.filter(slug => !order.includes(slug)).sort()];
  return Promise.all(slugs.map(async slug => ({
    ...JSON.parse(await readFile(path.join(CONTENT, `${slug}.json`), 'utf8')),
    slug
  })));
}

function jsString(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
}

function plantLiteral(plant) {
  const lines = [];
  for (const field of PLANT_FIELDS) {
    const value = plant[field];
    if (value === undefined || value === null || value === '' || (Array.isArray(value) && value.length === 0)) continue;
    lines.push(Array.isArray(value)
      ? `    ${field}: [${value.map(jsString).join(',')}]`
      : `    ${field}: ${jsString(value)}`);
  }
  const photos = (plant.photos || []).map(photo => jsString(`./assets/plants/${photo.file}`));
  lines.splice(4, 0, `    photos: [${photos.join(', ')}]`);
  return `  {\n${lines.join(',\n')}\n  }`;
}

function starterModule(plants) {
  return '// Generated by tools/build.mjs from content/plants. Edit the content files, not this one.\n'
    + `export const STARTER_PLANTS = [\n${plants.map(plantLiteral).join(',\n')}\n];\n`;
}

function photoSources(plants) {
  const rows = plants.flatMap(plant => (plant.photos || []).map(photo => {
    const license = photo.licenseUrl ? `[${photo.license}](${photo.licenseUrl})` : photo.license;
    const source = photo.sourcePage ? `[${photo.sourceFile}](${photo.sourcePage})` : photo.sourceFile || '';
    return `| \`assets/plants/${photo.file}\` | ${plant.commonName} | ${photo.shows || ''} | ${source} | ${photo.author || ''} | ${license || ''} |`;
  }));
  return ['# Photo Sources', '',
    'Generated by `tools/build.mjs` from `content/plants`. Edit the content files, not this one.', '',
    'Bundled starter photos are resized local copies from Wikimedia Commons. Keep this file with the image assets when redistributing the app.', '',
    'Each plant entry carries up to three photos chosen to show the whole plant, its leaves, and its flowers or fruit.', '',
    '| App file | Plant entry | Shows | Source file | Author | License |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows, '',
    'Notes', '',
    '- `Dicliptera tweediana` is treated here with `Dicliptera squarrosa` images because major taxonomic references list `Dicliptera tweediana` as a synonym of `Dicliptera squarrosa`.',
    '- The `Flechilla` and `Cola de zorro` starter entries are genus-level entries, so their bundled photos are representative species images: `Nassella neesiana` and `Setaria parviflora`.',
    '- The `Congorosa` entry uses images filed on Commons under both `Maytenus ilicifolia` and `Monteverdia ilicifolia`, which are the same species.',
    '- Photos are resized to fit 860 by 1150 pixels and re-encoded as progressive JPEG so the whole set stays small enough to cache offline.', ''
  ].join('\n');
}

async function updateServiceWorker(plants) {
  const file = path.join(ROOT, 'service-worker.js');
  const current = await readFile(file, 'utf8');
  const images = plants.flatMap(plant => (plant.photos || []).map(photo => `./assets/plants/${photo.file}`)).sort();
  const block = `const PLANT_IMAGES = [\n${images.map(image => `  '${image}'`).join(',\n')}\n];`;
  let next = current.replace(/const PLANT_IMAGES = \[[\s\S]*?\];/, block);
  if (next !== current) {
    next = next.replace(/my-garden-shell-v(\d+)/g, (_, n) => `my-garden-shell-v${Number(n) + 1}`);
  }
  await writeFile(file, next);
  return {images: images.length, bumped: next !== current};
}

function checkPhotos(plants) {
  const missing = [];
  for (const plant of plants) {
    for (const photo of plant.photos || []) {
      if (!existsSync(path.join(PHOTO_DIR, photo.file))) missing.push(`${plant.slug}: ${photo.file}`);
    }
  }
  return missing;
}

export async function build() {
  const plants = await loadPlants();
  const missing = checkPhotos(plants);
  if (missing.length > 0) throw new Error(`Missing photo files:\n  ${missing.join('\n  ')}`);
  await writeFile(path.join(ROOT, 'starter-plants.js'), starterModule(plants));
  await writeFile(path.join(ROOT, 'docs', 'PHOTO_SOURCES.md'), photoSources(plants));
  const sw = await updateServiceWorker(plants);
  return {plants: plants.length, photos: sw.images, cacheBumped: sw.bumped};
}

if (import.meta.url === `file://${process.argv[1]}`) {
  build().then(result => {
    console.log(`Built ${result.plants} plants, ${result.photos} photos.`);
    console.log(result.cacheBumped ? 'Service worker cache version bumped.' : 'Service worker unchanged.');
  }).catch(error => {
    console.error(error.message);
    process.exit(1);
  });
}
